name: test
on: push
jobs:
  test:
    runs-on: ubuntu22.04
    container: 
    image: KazuyaOchiai/ubuntu-22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2  #コンテナのカレントディレクトリにリポジトリを設置
      - name: build and test1
       run: |
         rsync -av ./ /root/robosys2024   #リポジトリの下をrobosys2024にコピー
         cd /root/robosys2024  #↓追加のパッケージが必要なら実行前にrosdep
         bash -xv ./reverse_text.bash /root    #実行   
